// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {docker} from '../models';
import {parser} from '../models';
import {semgrep} from '../models';

export function CheckDockerImagesIsAvailable(arg1:string,arg2:string):Promise<docker.DockerImage>;

export function CheckDockerIsAvailable():Promise<string>;

export function CheckIfFolderOrFIleExists(arg1:string):Promise<boolean>;

export function GetSemgrepReportData():Promise<parser.SemgrepReport>;

export function Greet(arg1:string):Promise<string>;

export function InitAndPrepareFolderScanSemgrep(arg1:string):Promise<void>;

export function RunSemgrepScan():Promise<semgrep.ScanResult>;
