// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDockerImagesIsAvailable(arg1, arg2) {
  return window['go']['main']['App']['CheckDockerImagesIsAvailable'](arg1, arg2);
}

export function CheckDockerIsAvailable() {
  return window['go']['main']['App']['CheckDockerIsAvailable']();
}

export function CheckIfFolderOrFIleExists(arg1) {
  return window['go']['main']['App']['CheckIfFolderOrFIleExists'](arg1);
}

export function CompleteFirstSetup(arg1) {
  return window['go']['main']['App']['CompleteFirstSetup'](arg1);
}

export function CreateNewRepo(arg1) {
  return window['go']['main']['App']['CreateNewRepo'](arg1);
}

export function CreateNewScan(arg1, arg2) {
  return window['go']['main']['App']['CreateNewScan'](arg1, arg2);
}

export function DeleteRepo(arg1, arg2) {
  return window['go']['main']['App']['DeleteRepo'](arg1, arg2);
}

export function DeleteScan(arg1, arg2) {
  return window['go']['main']['App']['DeleteScan'](arg1, arg2);
}

export function GetAndValidateUserByToken(arg1) {
  return window['go']['main']['App']['GetAndValidateUserByToken'](arg1);
}

export function GetRepoById(arg1, arg2) {
  return window['go']['main']['App']['GetRepoById'](arg1, arg2);
}

export function GetRepoDatas(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetRepoDatas'](arg1, arg2, arg3, arg4, arg5);
}

export function GetScanById(arg1, arg2) {
  return window['go']['main']['App']['GetScanById'](arg1, arg2);
}

export function GetScanDatas(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetScanDatas'](arg1, arg2, arg3, arg4, arg5);
}

export function GetScanDetail(arg1) {
  return window['go']['main']['App']['GetScanDetail'](arg1);
}

export function GetSemgrepReportData() {
  return window['go']['main']['App']['GetSemgrepReportData']();
}

export function InitAndPrepareFolderScanSemgrep(arg1) {
  return window['go']['main']['App']['InitAndPrepareFolderScanSemgrep'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function RunSemgrepScan() {
  return window['go']['main']['App']['RunSemgrepScan']();
}

export function UpdateRepo(arg1, arg2) {
  return window['go']['main']['App']['UpdateRepo'](arg1, arg2);
}

export function UpdateUserPassword(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserPassword'](arg1, arg2);
}

export function UpdateUserUsername(arg1) {
  return window['go']['main']['App']['UpdateUserUsername'](arg1);
}
