// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDockerImagesIsAvailable(arg1, arg2) {
  return window['go']['main']['App']['CheckDockerImagesIsAvailable'](arg1, arg2);
}

export function CheckDockerIsAvailable() {
  return window['go']['main']['App']['CheckDockerIsAvailable']();
}

export function CheckIfFolderOrFIleExists(arg1) {
  return window['go']['main']['App']['CheckIfFolderOrFIleExists'](arg1);
}

export function GetSemgrepReportData() {
  return window['go']['main']['App']['GetSemgrepReportData']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitAndPrepareFolderScanSemgrep(arg1) {
  return window['go']['main']['App']['InitAndPrepareFolderScanSemgrep'](arg1);
}

export function RunSemgrepScan() {
  return window['go']['main']['App']['RunSemgrepScan']();
}
